import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'
import { Authenticator } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'
import outputs from '../amplify_outputs.json'
import './index.css'
import App from './App.jsx'
import { NavigationProvider } from './context/NavigationProvider.jsx'
import { DecksProvider } from './context/DecksProvider.jsx'

// Must run AFTER the import block — src/api/decks.js builds its data client
// lazily for exactly this reason. `amplify_outputs.json` is generated by
// `npx ampx sandbox` locally and by the Amplify build in production.
Amplify.configure(outputs)

createRoot(document.getElementById('root')).render(
  <StrictMode>
    {/* Exposes the current user and sign-out via useAuthenticator(). It does
        NOT force login: the dictionary stays public, and only the Decks tab
        gates on auth. */}
    <Authenticator.Provider>
      {/* Both providers read the signed-in user, so both nest inside
          Authenticator.Provider. They stay separate from each other so
          changing tabs doesn't re-render every deck consumer, and vice versa. */}
      <NavigationProvider>
        <DecksProvider>
          <App />
        </DecksProvider>
      </NavigationProvider>
    </Authenticator.Provider>
  </StrictMode>,
)
