import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'
import { Authenticator } from '@aws-amplify/ui-react'
import '@aws-amplify/ui-react/styles.css'
import outputs from '../amplify_outputs.json'
import './index.css'
import App from './App.jsx'
import { NavigationProvider } from './context/NavigationProvider.jsx'
import { DecksProvider } from './context/DecksProvider.jsx'

// Connect the frontend to the Amplify backend (auth + data). `amplify_outputs.json`
// is generated by `npx ampx sandbox` locally and by the Amplify build in production.
Amplify.configure(outputs)

createRoot(document.getElementById('root')).render(
  <StrictMode>
    {/* Authenticator.Provider exposes the current user + sign-out to the whole
        app via the useAuthenticator() hook. It does NOT force login on its own —
        the dictionary stays public; only the Decks tab gates on auth. */}
    <Authenticator.Provider>
      {/* NavigationProvider sits inside Authenticator.Provider because it reads
          the signed-in user: adding a card requires login, so the deck picker
          redirects guests to the Decks tab instead of opening. */}
      <NavigationProvider>
        {/* Both providers read the signed-in user, so both go inside
            Authenticator.Provider. They're separate from each other so that
            changing tabs doesn't re-render every deck consumer, and vice versa. */}
        <DecksProvider>
          <App />
        </DecksProvider>
      </NavigationProvider>
    </Authenticator.Provider>
  </StrictMode>,
)
